fileURL <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
datafile <- "household_power_consumption.zip"
download.file(fileURL, datafile, method="curl")
downloadtime <- date()
print(downloadtime)
unzip(datafile, overwrite=TRUE)
initial <- read.table("household_power_consumption.txt", header=TRUE, sep=";", dec=".", na.strings="?", nrows=100, as.is=TRUE)
classes <- sapply(initial, class)
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", dec=".", na.strings="?", as.is=TRUE, colClasses=classes, comment.char="")
data2 <- subset(data, Date == "1/2/2007"| Date == "2/2/2007")
datetime <- as.POSIXct(strptime(paste(data2$Date, data2$Time), format="%d/%m/%Y %T", tz=""))
data3 <- cbind(datetime, data2[,c(3:9)])
png(filename="plot4.png", width=480, height=480)
par(mfrow=c(2,2))
Sys.setlocale("LC_TIME","C")
with(data3,plot(datetime,Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab=""))
with(data3,plot(datetime,Voltage,type="l"))
with(data3,plot(datetime,Sub_metering_1, type="l", col="black", ylab="Energy sub metering", xlab=""))
with(data3,lines(datetime,Sub_metering_2, col="red"))
with(data3,lines(datetime,Sub_metering_3, col="blue"))
legend("topright",legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), bty="n", lty=c(1, 1, 1), col=c( "black", "red", "blue"))
with(data3,plot(datetime,Global_reactive_power,type="l"))
dev.off()